[project]
name = "replay2025-hackaton-game-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "isort>=6.0.1",
    "ollama>=0.4.7",
    "temporalio>=1.10.0",
    "websockets>=15.0",
]
