[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "temporalio>=1.10.0",
    "websockets>=15.0",
]
